//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Year2015.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Year2015.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (((())))()((((((((())()(()))(()((((()(()(((()((()((()(()()()()()))(((()(()((((((((((())(()()((())()(((())))()(()(()((()(()))(()()()()((()((()(((()()(((((((()()())()((((()()(((((()(())()(())((())()()))()(((((((())(()())(()(((())(()))((())))(()((()())))()())((((())))(()(((((()(())(((()()((()((()((((((((((())(()())))))()))())()()((((()()()()()()((((((())())(((()())()((()()(((()()()))(((((()))(((()(()()()(()(()(((())()))(()(((()((())()(()())())))((()()()(()()(((()))(((()((((()(((((()()(()())((()())())(()((((((( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Input {
            get {
                return ResourceManager.GetString("Day1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20x3x11
        ///15x27x5
        ///6x29x7
        ///30x15x9
        ///19x29x21
        ///10x4x15
        ///1x26x4
        ///1x5x18
        ///10x15x23
        ///10x14x20
        ///3x5x18
        ///29x23x30
        ///7x4x10
        ///22x24x29
        ///30x1x2
        ///19x2x5
        ///11x9x22
        ///23x15x10
        ///11x11x10
        ///30x28x5
        ///22x5x4
        ///6x26x20
        ///16x12x30
        ///10x20x5
        ///25x14x24
        ///16x17x22
        ///11x28x26
        ///1x11x10
        ///1x24x15
        ///13x17x21
        ///30x3x13
        ///20x25x17
        ///22x12x5
        ///22x20x24
        ///9x2x14
        ///6x18x8
        ///27x28x24
        ///11x17x1
        ///1x4x12
        ///5x20x13
        ///24x23x23
        ///22x1x25
        ///18x19x5
        ///5x23x13
        ///8x16x4
        ///20x21x9
        ///1x7x11
        ///8x30x17
        ///3x30x9
        ///6x16x18
        ///22x25x27
        ///9x20x26
        ///16x21x23
        ///5x24x17
        ///15x17x15
        ///26x15x10
        ///22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Input {
            get {
                return ResourceManager.GetString("Day2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^&gt;&lt;^&gt;&gt;&gt;^&lt;^v&lt;v^^vv^&gt;&lt;&lt;^&lt;&gt;&lt;&lt;vv^&lt;&gt;^&lt;^v&gt;^vv&lt;&gt;v&gt;&lt;vv^^&lt;&gt;&gt;^^^v&lt;&lt;vv&gt;&lt;&lt;^&gt;^&lt;^v&lt;^&gt;^v&gt;&lt;&lt;&lt;v^&lt;v&lt;&lt;&lt;v&lt;&lt;vv&lt;v&lt;^&gt;&lt;^&gt;&gt;&lt;&gt;v&gt;v^&lt;&lt;v^^&lt;^v&lt;&gt;&lt;^&gt;^&lt;&lt;^^^&gt;v&gt;&gt;v^^&lt;v&gt;&gt;^&gt;vv&gt;&lt;v&gt;&gt;^&gt;&gt;v^&gt;^v&gt;^&lt;^^v&gt;^&gt;^^v&lt;v&gt;^^&lt;v&lt;&gt;&gt;v^^v&gt;&lt;^&gt;&lt;^&lt;&lt;&gt;v^&lt;^&lt;^v&lt;v&gt;v^&gt;&gt;&gt;v^v^&gt;^&lt;&gt;^v&lt;^^vv&lt;v&gt;^&gt;^&lt;&gt;^^&lt;vv^&lt;&gt;&lt;&lt;v&lt;^&lt;^^&gt;vv&lt;&gt;^&gt;v&lt;^&gt;^v&gt;v^&gt;^v&lt;&gt;^&gt;&lt;&gt;&gt;&lt;vv&lt;&gt;v^v&lt;&gt;&lt;&gt;v^v&gt;&gt;&gt;&gt;v^^&gt;^&gt;&lt;^^&lt;v&lt;^&gt;&lt;^&lt;v&gt;&gt;^v^v&lt;&gt;v&lt;&lt;&lt;^&lt;&lt;vvvv&lt;&lt;v^vv^&gt;v^^^&lt;^^^&lt;v&gt;&gt;v&lt;^v&gt;&gt;&gt;&gt;&gt;v&lt;^^^^&gt;v&lt;^&lt;&gt;&lt;v&gt;&gt;&gt;&gt;&gt;&lt;v&gt;&gt;v^vvvv^^&lt;v^&lt;&gt;^v&lt;^v^&gt;v&gt;&lt;^&gt;^v&lt;&lt;&gt;&gt;vv^&gt;v&gt;v^^&gt;vv^&lt....
        /// </summary>
        internal static string Day3Input {
            get {
                return ResourceManager.GetString("Day3Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yzbqklnj.
        /// </summary>
        internal static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sszojmmrrkwuftyv
        ///isaljhemltsdzlum
        ///fujcyucsrxgatisb
        ///qiqqlmcgnhzparyg
        ///oijbmduquhfactbc
        ///jqzuvtggpdqcekgk
        ///zwqadogmpjmmxijf
        ///uilzxjythsqhwndh
        ///gtssqejjknzkkpvw
        ///wrggegukhhatygfi
        ///vhtcgqzerxonhsye
        ///tedlwzdjfppbmtdx
        ///iuvrelxiapllaxbg
        ///feybgiimfthtplui
        ///qxmmcnirvkzfrjwd
        ///vfarmltinsriqxpu
        ///oanqfyqirkraesfq
        ///xilodxfuxphuiiii
        ///yukhnchvjkfwcbiq
        ///bdaibcbzeuxqplop
        ///ivegnnpbiyxqsion
        ///ybahkbzpditgwdgt
        ///dmebdomwabxgtctu
        ///ibtvimgfaeonknoh
        ///jsqraroxudetmfyw
        ///dqdbcwtpintfcvuz
        ///tiyphjunlxddenpj
        ///fgqwjgntxagidhah
        ///nwenhxma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5Input {
            get {
                return ResourceManager.GetString("Day5Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toggle 461,550 through 564,900
        ///turn off 370,39 through 425,839
        ///turn off 464,858 through 833,915
        ///turn off 812,389 through 865,874
        ///turn on 599,989 through 806,993
        ///turn on 376,415 through 768,548
        ///turn on 606,361 through 892,600
        ///turn off 448,208 through 645,684
        ///toggle 50,472 through 452,788
        ///toggle 205,417 through 703,826
        ///toggle 533,331 through 906,873
        ///toggle 857,493 through 989,970
        ///turn off 631,950 through 894,975
        ///turn off 387,19 through 720,700
        ///turn off 511,843 through 581,945
        ///toggle 514,557 thr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day6Input {
            get {
                return ResourceManager.GetString("Day6Input", resourceCulture);
            }
        }
    }
}
