// Copyright (c) Rory Claasen. All rights reserved.
// Licensed under the MIT license. See LICENSE in the project root for license information.

namespace AdventOfCode.Year2024.Tests;

using AdventOfCode.Shared.Tests;

[TestClass]
public class Day8SolutionTests : SolverBaseTests<Day8Solution>
{
    [TestMethod]
    [DataRow(@"............
............
............
............
............
......A.....
............
............
........A...
............
............
............", "2")]
    [DataRow(@"............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............", "14")]
    public void SolvePart1(string input, string answer)
    {
        var solvedAnswer = this.Solver.PartOne(input)?.ToString();
        Assert.AreEqual(answer, solvedAnswer);
    }

    [TestMethod]
    [DataRow(@"............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............", "34")]
    public void SolvePart2(string input, string answer)
    {
        var solvedAnswer = this.Solver.PartTwo(input)?.ToString();
        Assert.AreEqual(answer, solvedAnswer);
    }
}
