name: .Net

on:
  pull_request:
  push:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
      - name: Restore
        run: dotnet restore AdventOfCode.slnx
      - name: Build
        run: dotnet build AdventOfCode.slnx --configuration Release --no-restore
      - name: Test
        run: dotnet test --solution AdventOfCode.slnx --configuration Release --no-restore --no-build --results-directory ${{ github.workspace }}/artifacts/test-results -- --report-trx
      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: ${{ github.workspace }}/artifacts/test-results/*.trx
      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() && github.repository == 'roryclaasen/advent' }}
        with:
          name: Advent of Code Tests
          path: ${{ github.workspace }}/artifacts/test-results/*.trx
          reporter: dotnet-trx
          list-tests: failed

  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
          # - os: macos-latest
          #   rid: osx-x64
          - os: windows-latest
            rid: win-x64
          - os: windows-11-arm
            rid: win-arm64
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
      - name: Publish (AOT)
        run: dotnet publish AdventOfCode.slnx --configuration Release --runtime ${{ matrix.rid }} -p:PublishDir=${{ github.workspace }}/artifacts/bin/
      - name: Create Release Artifact
        uses: actions/upload-artifact@v7
        with:
          name: advent-${{ matrix.rid }}
          path: ${{ github.workspace }}/artifacts/bin/
